// Designed HTML announcement for the AI Camera + Field Tools, sent to
// inspectors from the Owner Mail Center (template id "ai-tools"). Uses hosted
// illustration PNGs from public/email/ (generated by scripts/gen-email-images.mjs).
// Email-client-safe: table layout, inline styles, images max-width 100%.

const APP_URL = "https://app.flowinspect.app";
const IOS_APP_URL = "https://apps.apple.com/us/app/flow-inspection-software/id6777555077";
const IMG = `${APP_URL}/email`;

function esc(s: string) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function figure(src: string, alt: string) {
  return `<img src="${src}" alt="${esc(alt)}" width="552" style="display:block;width:100%;max-width:552px;height:auto;border-radius:14px;border:1px solid #e2e8f0;margin:0 auto;" />`;
}

function h2(text: string) {
  return `<div style="font-size:20px;font-weight:900;color:#0f172a;margin:0 0 6px;">${esc(text)}</div>`;
}

function p(html: string) {
  return `<p style="font-size:15px;line-height:1.7;color:#334155;margin:0 0 14px;">${html}</p>`;
}

export const AI_TOOLS_SUBJECT = "The AI camera writes your findings for you";

// `firstName` is already resolved by the caller (never a raw email).
export function buildAiToolsEmail(firstName: string): string {
  const name = esc(firstName || "there");
  return `<div style="font-family:Arial,Helvetica,sans-serif;color:#0f172a;max-width:600px;margin:auto;padding:28px 24px;background:#ffffff;">

  <a href="${APP_URL}" style="text-decoration:none;">
    <img src="${APP_URL}/icons/icon-192-v2.png" alt="FLOW" width="46" height="46" style="border-radius:12px;vertical-align:middle;border:0;" />
    <span style="font-weight:900;font-size:22px;color:#14b8a6;vertical-align:middle;margin-left:11px;">FLOW</span>
  </a>

  <div style="margin-top:22px;">
    ${p(`Hi ${name},`)}
    ${p(`If you're still typing out every finding by hand, you're leaving hours on the table. Two tools in FLOW change that — here's a quick look at both.`)}
  </div>

  <div style="height:1px;background:#e2e8f0;margin:22px 0;"></div>

  ${h2("1. The AI Camera writes your findings")}
  ${p(`Point your phone at a defect, snap a photo or short video, and FLOW's AI writes the entire finding for you — <strong>title, severity, observation, implication, and recommendation</strong> — ready to approve with one tap. Shoot the same defect from a few angles and it merges them into one clean finding.`)}
  <div style="margin:6px 0 18px;">${figure(`${IMG}/ai-camera.jpg`, "Snap a defect photo and the AI writes the full finding")}</div>

  <div style="font-size:13px;font-weight:800;letter-spacing:0.06em;color:#0f766e;text-transform:uppercase;margin:0 0 8px;">How to open it</div>
  <div style="margin:0 0 16px;">${figure(`${IMG}/how-to-open.png`, "Open a report, tap Capture Tools then Field Tool, then the Live Camera tab")}</div>

  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:4px 0 8px;">
    <tr><td style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:12px;padding:14px 18px;">
      <span style="font-size:15px;line-height:1.6;color:#065f46;font-weight:700;">Time saved:</span>
      <span style="font-size:15px;line-height:1.6;color:#065f46;"> a 3–5 minute write-up per finding drops to a few seconds — that's an hour or two you get back on a typical inspection, every job.</span>
    </td></tr>
  </table>

  <div style="height:1px;background:#e2e8f0;margin:24px 0;"></div>

  ${h2("2. The Command Center — your whole report, one shortcut")}
  ${p(`Press <strong>Ctrl-K</strong> (or tap <strong>Open Command Center</strong>) on any report to get one workspace for AI safety review, publish blockers, signatures, payments, repair-request negotiation, and client engagement — with smart alerts that jump you straight to the finding that needs you.`)}
  <div style="margin:6px 0 18px;">${figure(`${IMG}/command-center.png`, "The Command Center workspace, opened with Ctrl-K")}</div>

  <div style="height:1px;background:#e2e8f0;margin:24px 0;"></div>

  ${h2("Bonus: no signal? no problem")}
  ${p(`Capture photos and quick notes with <strong>zero service</strong> — FLOW auto-uploads and AI-writes every finding the moment you're back online. Or use <strong>Bulk AI Capture</strong> to turn a whole camera roll of defect photos into clean, section-sorted, de-duplicated findings in a single review-and-save pass.`)}

  <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:22px 0 6px;">
    <tr>
      <td style="padding-right:12px;">
        <a href="${APP_URL}" style="display:inline-block;background:#14b8a6;color:#ffffff;font-weight:800;text-decoration:none;padding:13px 26px;border-radius:10px;">Open FLOW</a>
      </td>
      <td>
        <a href="${IOS_APP_URL}" style="display:inline-block;background:#0f172a;color:#ffffff;font-weight:800;text-decoration:none;padding:13px 26px;border-radius:10px;">Get the iOS App</a>
      </td>
    </tr>
  </table>

  ${p(`Give it a shot on your next inspection — then hit reply and tell me what you think. That's actually me on the other end.`)}
  ${p(`— Jeff`)}

  <p style="margin-top:24px;font-size:12px;color:#94a3b8;">You're receiving this because you have a FLOW inspector account.</p>
</div>`;
}
