#!/usr/bin/env node
// Scans app/ for page.tsx files and writes lib/appRoutes.generated.ts — the
// list of navigable app routes the command palette ("jump anywhere") offers.
// Runs automatically on predev/prebuild so a NEW page is always findable in
// search without anyone remembering to register it.
//
// Excluded on purpose: dynamic ([id]) routes (can't jump without context) and
// public/portal/client/auth/dev pages (not places an inspector "goes to").

import { readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const APP_DIR = join(process.cwd(), "app");
const OUT_FILE = join(process.cwd(), "lib", "appRoutes.generated.ts");

// Top-level segments that are NOT inspector/owner destinations.
const EXCLUDE_FIRST_SEG = new Set([
  "api",
  "login", "signup", "forgot-password", "reset-password", "onboarding",
  "client-portal", "client-agreement", "realtor-portal", "public-report",
  "share", "my-home", "my-reports", "repair-request", "repair-response",
  "environmental-report", "environmental-share", "demo",
  "payment-success", "payment-cancelled", "book", "embed",
  "pricing", "privacy", "terms", "code-assistant", "equipment-test", "inspectors",
]);
const EXCLUDE_EXACT = new Set(["/dashboard"]); // bare redirect; "/" is Home
// Segments that disqualify a route no matter where they appear.
const EXCLUDE_ANY_SEG = new Set(["payment-success", "payment-cancelled"]);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry === "page.tsx" || entry === "page.jsx") out.push(full);
  }
  return out;
}

function toRoute(file) {
  // app/foo/bar/page.tsx -> /foo/bar   (drop the filename, incl. the root)
  const rel = relative(APP_DIR, file).replace(/\\/g, "/").replace(/(^|\/)page\.(t|j)sx$/, "");
  const segs = rel.split("/").filter((s) => s && !/^\(.*\)$/.test(s)); // drop route groups (x)
  if (segs.some((s) => s.includes("["))) return null; // dynamic route
  if (segs.some((s) => EXCLUDE_ANY_SEG.has(s))) return null;
  return "/" + segs.join("/");
}

const routes = new Set();
for (const file of walk(APP_DIR)) {
  const route = toRoute(file);
  if (route === null) continue;
  const norm = route === "/" ? "/" : route.replace(/\/$/, "");
  const first = norm.split("/")[1] || "";
  if (EXCLUDE_EXACT.has(norm)) continue;
  if (EXCLUDE_FIRST_SEG.has(first)) continue;
  routes.add(norm || "/");
}

const sorted = [...routes].sort((a, b) => (a === "/" ? -1 : b === "/" ? 1 : a.localeCompare(b)));

const body = `// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Regenerated on predev/prebuild. Add curated labels/icons in CommandPalette.tsx.
export const GENERATED_ROUTES: string[] = [
${sorted.map((r) => `  ${JSON.stringify(r)},`).join("\n")}
];
`;

writeFileSync(OUT_FILE, body, "utf8");
console.log(`✅ Wrote ${sorted.length} routes to lib/appRoutes.generated.ts`);
